name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Format check (Prettier)
        run: npx prettier --check .

      - name: Lint check (ESLint)
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Run tests (Jest)
        run: npm test -- --ci
